{% set name = "large_image_source_rasterio" %}
{% set version = "1.29.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/large-image-source-rasterio-{{ version }}.tar.gz
  sha256: 9ac694e58b67a153b98c1d4d42471a494ab0280854179170691b696bb6d0a1f1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - large-image >=1.22.2
    - rasterio >=1.3
    - packaging

test:
  imports:
    - large_image
    - large_image_source_rasterio
  commands:
    - pip check
    - python -c "import large_image; large_image.tilesource.loadTileSources(); assert 'rasterio' in large_image.tilesource.AvailableTileSources"
  requires:
    - pip

about:
  home: https://github.com/girder/large_image
  summary: Python modules to work with large, multiresolution images - rasterio source
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  description: |
    Python modules to work with large, multiresolution images - rasterio source. Large Image is developed and maintained by the Data & Analytics group at Kitware, Inc. for processing large geospatial and medical images.
  doc_url: https://girder.github.io/large_image/
  dev_url: https://github.com/girder/large_image

extra:
  recipe-maintainers:
    - banesullivan
    - manthey
